services:
  - type: web
    name: gestion-proyecto-iub
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: DB_HOST
        value: be3e6usteto9qeznpfib-mysql.services.clever-cloud.com
      - key: DB_NAME
        value: be3e6usteto9qeznpfib
      - key: DB_USER
        value: uaubqipe9uapmd2z
      - key: DB_PASSWORD
        value: gWHf9tNMojmlIM5bCytI
      - key: DB_PORT
        value: "3306"
      - key: SECRET_KEY
        value: secret-key
